In [ ]:
#Problem 1
#No.1

import numpy as np

arr1 = np.empty((2,2))
print(arr1)

[[1.44989756e-315 0.00000000e+000]
 [6.58069148e-310 6.58069148e-310]]


In [ ]:
#No.2

arr1 = np.ones((4,2))
print(arr1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# No.3

arr1 = np.full((4,2),3)
print(arr1)

[[3 3]
 [3 3]
 [3 3]
 [3 3]]


In [ ]:
# No.4

arr1 = np.array([[1,2],
                [3,4]])
arr2 = np.zeros_like(arr1)
print(arr2)

[[0 0]
 [0 0]]


In [ ]:
# No.5
arr1 = np.array([[1,2],
                [3,4]])
arr2 = np.ones_like(arr1)
print(arr2)


[[1 1]
 [1 1]]


In [ ]:
# No.6

new_list = [1,2,3,4]
arr1 = np.array(new_list)
print(arr1)

[1 2 3 4]


# Problem 2

In [ ]:
#No.1

arr1 = np.arange(10,50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#No.2

arr1 = np.arange(0,9)
arr2 = arr1.reshape(3,3)
print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# No.3

arr1 = np.eye(3,3)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# No.4

arr1 = np.random.random(30)
meanOfArr1 = arr1.mean()
print(meanOfArr1)

0.46540141477700625


In [ ]:
# No.5
arr1 = np.random.randint(1,200,100)
arr2 = arr1.reshape(10,10)
print(arr2)

max = np.max(arr2)
min = np.min(arr2)
print(max)
print(min)

[[190 129  20  78  90   5  69 127  73  94]
 [ 78  21  81  12  84   6 166  84 171 193]
 [153  69  99  44  56  53  81 149 105  83]
 [136  87 136  48  75 162  27  53  74 194]
 [ 95 198 122  37  73 132  40  61  93  52]
 [ 28  39 167 103  49  50  99  39  10  96]
 [166 136 139 130 104  29  85  15  70  64]
 [ 50  35 106   3 177  31 199 190  77 111]
 [ 55 106 158 149   5 194  80 197  88 168]
 [170 192 184  10  58  69  62  23 123 160]]
199
3


In [ ]:
# No.6
arr1 = np.zeros(10)
print(arr1)

#Replacing the fifth element with 1
arr1[4] = 1
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#No.7

#Reversing an array
arr = np.array([1,2,0,0,4,0])
arr1 = arr[::-1]
print(arr1)

[0 4 0 0 2 1]


In [ ]:
#No.8

arr = np.ones((4,4))
print(arr)
print()
arr[1:3,1:3] = 0
#    ^-- selecting rows and second is columns
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [6]:
# No. 9
import numpy as np
arr = np.ones((8,8))
arr[1::2,::2] = 0
arr[::2,1::2] = 0

print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# Problem 3


In [33]:
import numpy as np

x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6],
              [7,8]])

v = np.array([9,10])
w = np.array([11,12])

print("Add x and y: ",np.add(x,y))
print("Add v and w: ",np.add(v,w))

print("Subtract y from x: ",np.subtract(x,y))
print("Subtract w from v: ",np.subtract(v,w))

#3 Multiply the arrays with any integers of choice
print("Multiplying x by 5: ",np.multiply(x,5))
print("Multiplying y by 5: ",np.multiply(y,5))
print("Multiplying v by 5: ",np.multiply(v,5))
print("Multiplying w by 5: ",np.multiply(w,5))

#4 FInd the square of each element of the array
print("The square of the elements of x are: ",(np.power(x,2)))
print("The square of the elements of y are: ",(np.power(y,2)))
print("The square of the elements of v are: ",(np.power(v,2)))
print("The square of the elements of w are: ",(np.power(w,2)))

#5 Find the dot product between: v(and)w ; x(and)v ; x(and)y.

print("The dot product between v and w is ", np.dot(v,w))
print("The dot product between x and v is ", np.dot(x,v))
print("The dot product between x and y is ", np.dot(x,y))

#6. Concatenate x(and)y along row and Concatenate v(and)w along column.

# Concatenating x and y along row (axis=0 or vstack)
np.concatenate((x,y),axis=0)
np.vstack((x,y))

# Concatenating v(and) w along the column (axis =1) or h stack
np.concatenate((v,w),axis=0) # they are 1D arrays so they only have one axis(axis 0)
np.hstack((v,w))

#Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
np.vstack((x,v))
# np.hstack((x,v)) we get an error while doing this because  the number of rows don't match




Add x and y:  [[ 6  8]
 [10 13]]
Add v and w:  [20 22]
Subtract y from x:  [[-4 -4]
 [-4 -3]]
Subtract w from v:  [-2 -2]
Multiplying x by 5:  [[ 5 10]
 [15 25]]
Multiplying y by 5:  [[25 30]
 [35 40]]
Multiplying v by 5:  [45 50]
Multiplying w by 5:  [55 60]
The square of the elements of x are:  [[ 1  4]
 [ 9 25]]
The square of the elements of y are:  [[25 36]
 [49 64]]
The square of the elements of v are:  [ 81 100]
The square of the elements of w are:  [121 144]
The dot product between v and w is  219
The dot product between x and v is  [29 77]
The dot product between x and y is  [[19 22]
 [50 58]]


array([[ 1,  2],
       [ 3,  5],
       [ 9, 10]])

# Problem 4

In [37]:
#1 A.AInverse = I

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

aInverse = np.linalg.inv(A)
print(aInverse)
product = np.dot(A,aInverse)
print(np.round(product,10)) #ROunding the elements of the array to 10 decimal places



[[-2.    1.  ]
 [ 1.75 -0.75]]
[[1. 0.]
 [0. 1.]]


In [40]:
# AB  != BA


A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

ab = np.dot(A,B)
ba = np.dot(B,A)
if(np.array_equal(ab,ba)):
  print("AB is equal to BA")
else:
  print("AB is not equal to BA")

AB is not equal to BA


In [42]:
#Prove (AB)Transpose = B Transpose A Transpose

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

ab = np.dot(A,B)
abTranspose = ab.T

bTranspose = B.T
aTranspose = A.T

dotBtAt = np.dot(bTranspose,aTranspose)

if(np.array_equal(abTranspose,dotBtAt)):
    print(True)



True


In [45]:
'''
Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
'''

A = np.array([[2,-3,1],
             [1,-1,2],
             [3,1,-1]])
B = np.array([[-1],
             [-3],
             [9]])

A_Inverse = np.linalg.inv(A)
X = np.dot(A_Inverse,B)
print(X)

[[ 2.]
 [ 1.]
 [-2.]]
